# https://github.com/settings/installations/5095422

# Number of days of inactivity before an issue becomes stale
daysUntilStale: 30

# Number of days of inactivity before a stale issue is closed
daysUntilClose: 15

# Issues with these labels will never be considered stale
exemptLabels:
  - pinned

# Label to use when marking an issue as stale
staleLabel: 'status: stale'

markComment: >
  Marking this issue as stale, because it has not had recent activity.
  It will be closed if no further activity occurs.
  Thanks

  :alien:
