os: linux

services:
  - docker

git:
  depth: 2
  quiet: true

branches:
  only:
    - master
    - stage

env:
  global:
    - NODE_ENV=production

before_install:
  - echo "$SSH_KEY" > ./key
  - chmod 600 ./key
  - echo -e "Host $SSH_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - eval `ssh-agent -s`
  - ssh-add ./key

install: skip

script: skip

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    all_branches: true
