os: linux

git:
  depth: 2
  quiet: true

branches:
  only:
    - master
    - stage

env:
  global:
    - NODE_ENV=production

install: skip

before_script:
  - echo -e "Host github.com\n\tHostName github.com\n\tUser git\n\tIdentityFile ~/.ssh/id_rsa\n" >> ~/.ssh/config

script: skip

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    all_branches: true
