name: Newcomer Greetings

on: [pull_request, issues]

jobs:
  greetings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: ':clap: thanks for creating an issue here :balloon:'
          pr-message: ':clap: congrats on your first PR here :balloon:'
